### ISSUE TITLE
Wrong item type when using Maybe.map

### ISSUE THREAD

**Issue by davidtang10** [true-myth/true-myth#51] opened 2019-09-03 00:24 UTC
Hi, nice project. I'm using it to unwrap data from a graphql API however when I try to use the map method on the data the type is the array itself instead of the item in the array.

Here is an example of the data I get from the API.

```javascript
const data = {
    camera: [
      {
        id: 1,
        name: 'camera1',
        location: { id: 1, name: 'location1' },
      },
      {
        id: 2,
        name: 'camera2',
        location: { id: 2, name: 'location2' },
      }
    ]
  }
```
This is the error I get using Maybe.map

```javascript
 const locations = Maybe.of(data)
    .get('camera')
    .map(camera => camera.location); // Property 'location' does not exist on type 'CameraFragment[]'
```

Using Array.prototype.map

```javascript
 const locations = Maybe.of(data)
    .get('camera')
    .unwrapOr([])
    .map(camera => camera.location); // type is correctly outputting the item CameraFragment
```

Right now I'm unwrapping it first then using Array.prototype.map to map it and it's working but I'm wondering why it's giving me the wrong type when I use Maybe.map. The types are generated using graphql-codegen so maybe that's the problem? Array.prototype.map works fine with them though. Am I missing something?

**Comment by chriskrycho** [comment] 2019-09-03 03:19
First, thanks for the kind words!

Second, the problem here is not with the library! Your confusion is understandable, though; I'll try to give a brief explanation here and then direct you to the docs!

From reading your question, it seems that you think `map` here is specifically meant to be the same as `Array.prototype.map`, but it's not!

`map` is a function (or, in this case, method) that can be defined fo a bunch of different types, not only `Array`: it's the general concept of applying a transformation to a value in a given context—whether that context is an array, a hash map, a `Maybe`, a `Result`, or some other type you come up with. (The technical name for this is a "functor," if you're curious.)

You can see this with the types. The type of `Array.prototype.map` looks roughly like this (I've left out some extra bits that don't matter for our purposes):

```ts
interface Array<T> {
  map<U>(callbackfn: (value: T) => U): U[];
}
```

The type of `Maybe.map` looks like this (again, leaving out a couple details that are irrelevant to our purposes):

```ts
interface Maybe<T> {
  map<U>(callbackfn: (value: T) => U): Maybe<U>;
}
```

Notice that they do the same basic thing—they take a callback to transform what is in the `Array` or the `Maybe`—but they're *not* the same function. One of them transforms things inside `Array`; the other inside `Maybe`. True Myth's `Result` has the same function for the `Ok` variant (and `mapErr` for the `Err` variant).

If you wanted to, you could write the same thing to map the values of a `Set`:

```ts
```ts
interface Set<T> {
  map<U>(callbackFn: (value: T) => U): Set<U>;
}
```

Or for `Map`, JS's built-in hash-map type (`map` with `Map` is a lot of "map" :scream:):

```ts
interface Map<K, T> {
  map<U>(callbackFn: (value: T) => U): Map<K, U>;
}
```

We could even map over the keys of a `Map`:

```ts
interface Map<K, T> {
  mapKeys<L>(callbackFn: (key: K) => L): Map<L, T>;
}
```

(The implementations for these would be a little complicated to do *well* performance-wise, but you *could* implement them.)

I think you may find the example given [here][1] in the README helpful: it uses `Maybe.map` to show how it's *like* `Array.prototype.map` but for `Maybe` instead of `Array`.

[1]: https://github.com/true-myth/true-myth#how-it-works-maybe

Now, why do we want this behavior? Well, as [that example][1] shows, because it lets us do something if the item is present, but *not* if it isn't. That top-level `Maybe.of(data)` gives you something roughly like `Maybe<{ cameras: CameraData[] }>`. When we do `.get('camera's)`, we have to account for the fact that `data` *might not have been there*. So what we get back is a `Maybe` of the type at `'cameras'`—that way, it's `Nothing` if `data` was `null` or `undefined`, but it's still safe because the `Maybe` is handling that for us. The type at `'cameras'` is `CameraFragment[]`, so what we have no is `Maybe< CameraFragment[]>`. Now, given how your schema is defined, if you have `data` at all, you have an array there… but you might not have had `data`! That's why there's the extra layer here.

We can see this clearly if we drop `Maybe` from the equation:

```ts
let data = fetchViaGraphQL();
```

Presumably, `data` here is something like `null | { cameras: CameraFragment[] }` because the API might not have given us any data. We have to account for that:

```ts
if (data !== null) {
  const locations = data.cameras.map(camera => camera.location);
}
```

If we *didn't* do the check `!== null`, this would sometimes give us the runtime exception:

> TypeError: null is not an object (evaluating 'data.cameras')

*That's* what we're working around with `Maybe`! `Maybe.get(...).unwrapOr(...)` is the equivalent of doing this:

```ts
const cameras = data !== null ? data.cameras : [];
const locations = cameras.map(camera => camera.location);
```

In this specific case, because `cameras` itself isn't optional, you don't need the `get` part at all:

```ts
const locations = Maybe.of(data)
  .map(data => data.cameras.map(camera => camera.locations))
  .unwrapOr([]);
```

And that `unwrapOr` is pretty common, so you can actually just write *this*:

```ts
const locations = Maybe.of(data)
  .mapOr([], data => data.cameras.map(camera => camera.locations));
```

For more, I recommend taking a close read through [the `Maybe` docs](https://true-myth.js.org/modules/_maybe_.html) and especially [the docs for `Maybe.map`](https://true-myth.js.org/modules/_maybe_.html#map)!

I'm going to go ahead and close this issue since it's not a bug, but please feel free to follow up with further questions if you have any!

**Closed by chriskrycho** 2019-09-03 03:19 UTC

**Comment by davidtang10** [comment] 2019-09-03 04:48
Thank you so much for explaining it to me. Sorry to waste your time with this.

I understand now. I'm new to functional programming so I did mistakenly think it was the same as `Array.prototype.map`.

**Comment by chriskrycho** [comment] 2019-09-03 13:04
No problem at all, and please don’t worry or feel bad about asking! It was not a waste of my time! I guessed from your question this was new to you, and was very happy to explain. We’ve always aimed for the library to be a good jumping on point for people unfamiliar with functional programming, and are very happy to clear things up when there’s confusion!
